# Generated by Django 2.0.3 on 2018-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=30)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('given_time', models.TimeField()),
                ('lineno', models.BigIntegerField()),
            ],
        ),
    ]
