# Generated by Django 2.0.3 on 2018-03-26 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='QR',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
